### ISSUE TITLE
garousp doesn't boot up

### ISSUE THREAD

**Issue by Tatsuya79** [libretro/px68k-libretro#48]
Garou Densetsu Special from Mame software list set (garousp) fails to boot while it runs in Mame and XM6 type G.
It's a dim floppy image, [and it seems to load some drivers.](https://postimg.org/image/1skytcol0r/)
Typing dir shows no file at all.

**Comment by retro-wertz** [comment]
forgot the actual name, but these are floppies written by special method,
so cannot normally use dos to see filesystem.

**Comment by Tatsuya79** [comment]
Jotei3 and jotei4 seem to do something similar.

**Comment by retrofan2019** [comment]
i confirm that this problem still persists ... not only the floppy disks working fine in mame/xm6 and winx68 and not working in the core ... the installed version of the disks to an hdf hdd image works fine on xm6 and winx68 but won't load in the core ... tries to run the main file  and just stays frozen there forever ..

**Comment by Tatsuya79** [comment]
I've been testing a hdf version again, it's stuck after boot on that screen:
![GAROU DENSETSU SPECIAL-px68k](https://github.com/user-attachments/assets/85e2664a-20a0-4a7d-8ee7-6e08b4574072)

The error message says:

"SCSI call error recorded.
A failed writing handshake from drive id3 has been corrected.
Writing block size is 256 bytes."

This error message appears on other games boot and they still work fine in px68k.

Testing that same hdf in xm6 type-G, you don't see that error message and the game is working fine.

**Comment by negativeExponent** [comment]
those device drivers dont matter. i have modified the HD file and remove config.sys and autoexec.bat from running on startup and instead run !Start.bar manually, game still wont work. while XM6 pro runs fine that way.

still dont have a clue where the issue is (probably dma, or something timing related)

**Comment by Tatsuya79** [comment]
Indeed, I just found a different hdd image without that error message and it's stuck there still.

Another possibility; that's a copy protection and I just saw that note:
"Oh! Also, the key disk is absolutely necessary. Insert it in the 0 drive (you're not a copy user, are you?)."

https://tcrf.net/Garou_Densetsu_Special_(Sharp_X68000)

**Comment by Tatsuya79** [comment]
WinX68k高速版/HighSpeed fixed that game not booting up on version 0.85.
Of course it's closed source...

Release notes:

```2003.07.25 v0.85をリリース
	   $E80481の画像取り込み用ビットがセットされた時の動作を修正（大戦略III）
	   インターレース時のグラフィック高速クリアの動作タイミングをより実機に近づける
	   FDCのSENSE INTERRUPT STATUSコマンドの動作を修正（TWIN COPY、The File Master）
	   FDCのヘッド位置をより正確に再現するようにする（デスブリンガー）
	   MFPのGPIPレジスタからの読み出し値を実機に近づける
	   DIM形式イメージを読み込み専用にする
	   MPUデバッグ時に特定のI/Oレジスタ値を表示している場合の動作不具合を修正
	   DMACの割り込み処理を修正（Moon Fighter）
	   DMACチャンネル３（ADPCM関連）の動作を修正

Google translation:

Fixed behavior when $E80481 image capture bit is set (Dai Senryaku III)
Modified timing of graphics high-speed clear operation during interlacing to be closer to the actual device
Modified behavior of FDC SENSE INTERRUPT STATUS command (TWIN COPY, The File Master)
Modified FDC head position to be reproduced more accurately (Deathbringer)
Modified read values ​​from MFP GPIP registers to be closer to the actual device
Made DIM format images read-only
Fixed malfunction when displaying specific I/O register values ​​during MPU debugging
Modified DMAC interrupt processing (Moon Fighter)
Modified behavior of DMAC channel 3 (ADPCM related)```
